# Generated by Django 4.1.8 on 2023-05-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('PT', 'Python'), ('C#', 'C#'), ('C++', 'C++'), ('Go', 'Go'), ('JS', 'JavaScript'), ('Java', 'Java'), ('Sh', 'Shell')], max_length=4)),
                ('category', models.CharField(choices=[('AG', 'Algorithms'), ('WD', 'Web-development'), ('SC', 'Scripts'), ('PY', 'Poetry'), ('PR', 'Programming')], max_length=2)),
                ('is_private', models.BooleanField()),
                ('short_url', models.CharField(default='', max_length=8)),
            ],
        ),
    ]
