# Generated by Django 4.1.8 on 2023-05-02 20:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paste',
            name='category',
            field=models.CharField(choices=[('AG', 'Algorithms'), ('WD', 'Web-development'), ('SC', 'Scripts'), ('PY', 'Poetry'), ('PR', 'Programming'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='paste',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paste',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 23, 44, 40, 139810)),
        ),
    ]
