# Generated by Django 4.1.8 on 2023-05-02 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syt_app', '0003_alter_paste_author_alter_paste_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
