# Generated by Django 4.1.8 on 2023-05-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syt_app', '0005_alter_paste_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='short_url',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
