# Generated by Django 4.2.1 on 2023-05-17 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syt_app', '0006_alter_paste_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
